site_name: Crossworld Docs
site_description: Игровая и техническая документация
site_url: https://credodocs.github.io/crossworld.github.io/

theme:
  name: material
  font:
    text: "Fira Code"
  language: ru
  logo: assets/favicon.ico
  favicon: assets/favicon.ico

  palette: 
    scheme: slate
    primary: indigo
    accent: deep purple
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.tabs
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - content.code.copy
    - toc.follow
    - search.suggest
  

# extra_css:
#   - stylesheets/catppuccin.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - drawio:
      darkmode: true
  - meta
  - tags

extra_javascript:
  - https://viewer.diagrams.net/js/viewer-static.min.js
  - javascripts/drawio-reload.js

nav:
  - Главная: index.md
  - Истории: 
    - nd/index.md
    - Проводник Смерти: 
      - nd/dg/index.md
      - 1 Глава: nd/dg/chapters/01.md
      - 2 Глава: nd/dg/chapters/02.md
      - Персонажи: 
        - nd/dg/characters/index.md
        - Гаэль: nd/dg/characters/gael.md
        - Даин: nd/dg/characters/dain.md
        - Гретель: nd/dg/characters/gretel.md
        - Мария: nd/dg/characters/maria.md
        - Ганс: nd/dg/characters/hans.md
        - Кот: nd/dg/characters/cat.md
        - Зиль: nd/dg/characters/zill.md
        - Марта: nd/dg/characters/marta.md
        - Кель: nd/dg/characters/kel.md
        - Вель: nd/dg/characters/vel.md
  - ГДД: gdd/index.md
  - Арт: 2d/index.md
  - UI: ui/index.md

extra:
  status:          
    draft: Черновик
    wip: В работе
    review: На проверке
    current: Актуально
    deprecated: Устарело